# Generated by Django 4.2.6 on 2025-11-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='acompanhamentos',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='prato_secundario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
