# Generated by Django 5.2.8 on 2025-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cardapio_acompanhamentos_cardapio_prato_secundario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='token_confirmacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
